import Area from "./area";
import Bed from "./bed";
import Email from "./email";
import Feature1 from "./feature1";
import Gym from "./gym";
import HealthCareCentre from "./healthCareCentre";
import InternationalSchool from "./internationalSchool";
import Key from "./key";
import LeftArrow from "./leftArrow";
import Location from "./location";
import Payment1 from "./payment1";
import Payment2 from "./payment2";
import Payment3 from "./payment3";
import PlayArea from "./playArea";
import Restaurants from "./restaurants";
import RetailOutlets from "./retailOutlets";
import RightArrow from "./rightArrow";
import SwimmingPool from "./swimmingPool";
import Whatsapp from "./whatsapp";

export const area = <Area />;
export const bed = <Bed />;
export const key = <Key />;
export const location = <Location />;
export const feature1 = <Feature1 />;
export const gym = <Gym />;
export const retailOutlets = <RetailOutlets />;
export const restaurants = <Restaurants />;
export const healthCareCentre = <HealthCareCentre />;
export const internationalSchool = <InternationalSchool />;
export const payment1 = <Payment1 />;
export const payment2 = <Payment2 />;
export const payment3 = <Payment3 />;
export const playArea = <PlayArea />;
export const swimmingPool = <SwimmingPool />;
export const leftArrow = <LeftArrow />;
export const rightArrow = <RightArrow />;
export const whatsapp = <Whatsapp />;
export const email = <Email />;
